version: '3'

services:
  chain0:
    container_name: chain0
    storage_opt:
      size: '5G'
    build: .
    command: ignite chain serve -v
    networks:
      baton-chain-net:
        ipv4_address: 192.167.10.2

  chain1:
    container_name: chain1
    storage_opt:
      size: '5G'
    build: .
    command: ignite chain serve --config config2.yml -v
    networks:
      baton-chain-net:
        ipv4_address: 192.167.10.3

  chain2:
    container_name: chain2
    storage_opt:
      size: '5G'
    build: .
    command: ignite chain serve --config config3.yml -v
    networks:
      baton-chain-net:
        ipv4_address: 192.167.10.4

  relayer1:
    container_name: relayer1
    build:
      dockerfile: ./DockerfileRelayer1
    networks:
      baton-chain-net:
        ipv4_address: 192.167.10.5

  relayer2:
      container_name: relayer2
      build:
        dockerfile: ./DockerfileRelayer2
      networks:
        baton-chain-net:
          ipv4_address: 192.167.10.6

networks:
  baton-chain-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.167.10.0/16