version: '3'

services:
  chain0:
    container_name: chain0
    build: .
    ports:
      - "26656-26657:26656-26657"
    volumes:
      - ./build/chain0/evmosd:/evmos:Z
    command:
      - ignite chain server -v
    networks:
      baton-chain-net:
        ipv4_address: 192.167.10.2

networks:
  baton-chain-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.167.10.0/16